// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WhatThe.Mods.CitiesSkylines.Asseteer.Reporter.Template
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class HtmlReportTemplate : HtmlReportTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 5 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 Minify = true; 
            
            #line default
            #line hidden
            this.Write("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<meta charset=\"UTF-8\" />\r\n<meta http-equiv=\"Cont" +
                    "ent-Type\" content=\"text/html;charset=UTF-8\">\r\n<meta name=\"generator\" content=\"");
            
            #line 11 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BuildInfo));
            
            #line default
            #line hidden
            this.Write("\" />\r\n<title>Asset Report</title>\r\n<style type=\"text/css\">");
            this.Write(@"body{font-family:sans-serif;color:#91d8ff;background-color:#060607;}table{color:#060607;background-color:#368cd0;border-collapse:collapse;margin-top:1em;margin-bottom:2em;margin-left:1em;margin-right:1em;table-layout:fixed;}table,th,td{border:1px solid #0a5486;}td,th{padding:8px;}thead{color:#91d8ff;background-color:#103474;}tbody{color:#060607;background-color:#368cd0;}tbody tr{background-color:#368cd0;}tbody tr.table-row-odd{background-color:#2c6bad;}th{text-align:center;font-size:75%;text-transform:capitalize;}td a{color:#060607;text-decoration:underline #114069;}tr.table-headers th{font-variant:small-caps;}span.name,td.nam{white-space:nowrap;}td.num,th.num,td.dim,th.dim{text-align:right;}td.txt,td.nam,th.txt{text-align:left;}th.table-sortable:before{content:""▽△"";}th.table-sorted-desc:before{content:""▽▲"";}th.table-sorted-asc:before{content:""▼△"";}th.table-filtered span:after{display:block;float:right;content:""⌔"";}select.table-autofilter{background-color:#103474;color:#01b9ff;border-color:#0a5486;outline-color:#0a5486;}.link,table.main-table tr.column-headers th{cursor:pointer;}.showhide,.depshow,.dephide,.refshow,.refhide{color:#01b9ff;text-decoration:none;}.depshow,.dephide,.refshow,.refhide{float:right;}.top-table-showhide{float:left;}.miss{color:#aa0132;}");
            this.Write("</style>\r\n<script language=\"javascript\" type=\"text/javascript\">");
            this.Write("/* Copyright (c)2005-2009 Matt Kruse (javascripttoolbox.com) Dual licensed under " +
                    "the MIT and GPL licenses. This basically means you can use this code however you" +
                    " want for free, but don\'t claim to have written it yourself! Donations always ac" +
                    "cepted: http://www.JavascriptToolbox.com/donate/ */ eval(function(p,a,c,k,e,d){e" +
                    "=function(c){return(c<a?\'\':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+2" +
                    "9):c.toString(36))};if(!\'\'.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=" +
                    "[function(e){return d[e]}];e=function(){return\'\\\\w+\'};c=1};while(c--){if(k[c]){p" +
                    "=p.replace(new RegExp(\'\\\\b\'+e(c)+\'\\\\b\',\'g\'),k[c])}}return p}(\'6 1C=(9(){6 q={};q" +
                    ".23=9(a,b){h(a==b)?0:(a<b)?-1:1};q[\\\'2M\\\']=q.23;q.2S=9(33){h 9(w){5(X(w)==\"3B\"){" +
                    "w=4n(w.1R(/^[^\\\\d\\\\.]*([\\\\d., ]+).*/g,\"$1\").1R(1e 17(\"[^\\\\\\\\\\\\d\"+33+\"]\",\"g\"),\\\'\\" +
                    "\').1R(/,/,\\\'.\\\'))||0}h w||0}};q.1n=9(a,b){h q.1n.O(a)-q.1n.O(b)};q.1n.O=q.2S(\".\"" +
                    ");q.1I=9(a,b){h q.1I.O(a)-q.1I.O(b)};q.1I.O=q.2S(\",\");q.1T=9(a,b){h q.23(q.1T.O(" +
                    "a),q.1T.O(b))};q.1T.O=9(w){5(w==C){h\"\"}h(\"\"+w).4k()};q.4f=q.1n;q.4e=q.1I;q.16=9(" +
                    "a,b){h q.1n(q.16.O(a),q.16.O(b))};q.16.2P=9(19){19=+19;5(19<4G){19+=4u}M 5(19<4w" +
                    "){19+=4x}h 19};q.16.2Y=[{1S:/(\\\\d{2,4})-(\\\\d{1,2})-(\\\\d{1,2})/,f:9(x){h(1e 2I(q." +
                    "16.2P(x[1]),+x[2],+x[3])).2K()}},{1S:/(\\\\d{1,2})[\\\\/-](\\\\d{1,2})[\\\\/-](\\\\d{2,4})" +
                    "/,f:9(x){h(1e 2I(q.16.2P(x[3]),+x[1],+x[2])).2K()}},{1S:/(.*\\\\d{4}.*\\\\d+:\\\\d+\\\\d" +
                    "+.*)/,f:9(x){6 d=1e 2I(x[1]);5(d){h d.2K()}}}];q.16.O=9(w){6 m,v,f=q.16.2Y;F(6 i" +
                    "=0,L=f.y;i<L;i++){5(m=w.1Q(f[i].1S)){v=f[i].f(m);5(X(v)!=\"2H\"){h v}}}h 43};h q})" +
                    "();6 1K=(9(){9 G(o){h(X o!=\"2H\")};9 14(o,1a){h 1e 17(\"(^|\\\\\\\\s)\"+1a+\"(\\\\\\\\s|$)\")" +
                    ".41(o.10)};9 1l(o,1a){6 c=o.10||\"\";5(G(c)&&!14(o,1a)){o.10+=(c?\" \":\"\")+1a}};9 1k" +
                    "(o,1a){6 c=o.10||\"\";o.10=c.1R(1e 17(\"(^|\\\\\\\\s)\"+1a+\"(\\\\\\\\s|$)\"),\"$1\")};9 Y(o,34)" +
                    "{6 c=o.10;5(c.1Q(1e 17(\"(^|\\\\\\\\s)\"+34+\"([^ ]+)\"))){h 17.$2}h C};9 1A(o){5(1c.3g)" +
                    "{6 3f=1c.3g;h(1A=9(o){h\\\'24\\\'==3f(o,C).3Y(\\\'1B\\\')})(o)}M 5(1c.3i){h(1A=9(o){h\\\'2" +
                    "4\\\'==o.3i[\\\'1B\\\']})(o)}h(1A=9(o){h\\\'24\\\'==o.2N[\\\'1B\\\']})(o)};9 1M(o,a,b){5(o!=C&" +
                    "&o.W){5(o.W==a||(b&&o.W==b)){h o}1q(o=o.1Z){5(o.W&&(o.W==a||(b&&o.W==b))){h o}}}" +
                    "h C};9 3a(2J,3k){F(6 i=2;i<3j.y;i++){6 a=3j[i];5(G(2J[a])){3k[a]=2J[a]}}}6 7={3x" +
                    ":\"7-45\",3y:\"7-12:\",3J:\"7-29\",3z:\"7-29:\",3A:\"3X 4a q\",2v:\"7-37-4b\",2x:\"7-37-1d\",2" +
                    "e:\"7-36\",3E:\"7-36:\",2X:\"7-46\",2D:\"7-2y\",3q:\"7-38\",2w:\"7-47\",3l:\"7-38-3c:\",3d:\"7-" +
                    "3c:\",2W:\"3R: 3P\",3v:\"7-2L:\",3u:\"7-B:\",3H:\"7-B-3Q:\",3t:\"7-B-2i:\"};7.S={};7.3b=1;7" +
                    ".T=9(o,p){5(o!=C&&o.W&&o.W!=\"2d\"){o=1M(o,\"2d\")}5(o==C){h C}5(!o.I){6 I=C;1y{6 I=" +
                    "\"3S\"+(7.3b++)}1q(1j.1J(I)!=C);o.I=I}n.S[o.I]=n.S[o.I]||{};5(p){3a(p,n.S[o.I],\"12" +
                    "\",\"3I\",\"1U\",\"R\",\"D\",\"1d\",\"B\",\"P\")}h o};7.1s=9(t,E,1o,1H){t=n.T(t);5(t==C){h}5(E!" +
                    "=\"3p\"){n.2C(t.3V,1o,1H)}5(E!=\"1g\"){n.2C(t.3U,1o,1H)}};7.2C=9(1v,1o,1H){5(1v!=C){" +
                    "5(1v.J&&1v.J.y&&1v.J.y>0){6 J=1v.J;F(6 j=0,1r=J.y;j<1r;j++){6 V=J[j];5(V.A&&V.A." +
                    "y&&V.A.y>0){6 A=V.A;F(6 k=0,39=A.y;k<39;k++){6 35=A[k];1o.4i(n,35,1H)}}}}}};7.1h" +
                    "=9(Z){6 2j=Z.1Z;6 A=2j.A;5(A&&A.y){5(A.y>1&&A[A.y-1].1D>0){(n.1h=9(Z){h Z.1D})(Z" +
                    ")}F(6 i=0,L=A.y;i<L;i++){5(2j.A[i]==Z){h i}}}h 0};7.1E={\\\'3K\\\':9(H){5(G(H.1w)&&H" +
                    ".E&&((H.E!=\"4v\"&&H.E!=\"4y\")||H.4z)){h H.1w}h\"\"},\\\'3O\\\':9(H){5(H.22>=0&&H.2t){h H" +
                    ".2t[H.22].3L}h\"\"},\\\'4d\\\':9(H){h H.1a||\"\"}};7.1z=9(Z,3e){5(3e&&G(Z.1W)){h Z.1W}5(" +
                    "!Z.1G){h\"\"}6 1G=Z.1G;6 1u=\"\";F(6 i=0,L=1G.y;i<L;i++){6 H=1G[i];6 E=H.4A;5(E==1){" +
                    "6 2o=H.W;5(n.1E[2o]){1u+=n.1E[2o](H)}M{1u+=n.1z(H)}}M 5(E==3){5(G(H.1W)){1u+=H.1" +
                    "W}M 5(G(H.1E)){1u+=H.1E}}}h 1u};7.1m={};7.2g=9(1t){5(!G(1t.1D)){h C}6 1p=1M(1t,\"" +
                    "2d\");6 2E=1t.1Z.15+\"-\"+n.1h(1t);5(G(n.1m[1p.I])){h n.1m[1p.I][2E]}6 1i=[];n.1m[1" +
                    "p.I]={};6 3h=1M(1t,\"1g\");6 2G=3h.31(\\\'4r\\\');F(6 i=0;i<2G.y;i++){6 A=2G[i].A;F(6 " +
                    "j=0;j<A.y;j++){6 c=A[j];6 15=c.1Z.15;6 3m=15+\"-\"+n.1h(c);6 2A=c.2A||1;6 2F=c.2F|" +
                    "|1;6 1L;5(!G(1i[15])){1i[15]=[]}6 m=1i[15];F(6 k=0;k<m.y+1;k++){5(!G(m[k])){1L=k" +
                    ";4h}}n.1m[1p.I][3m]=1L;F(6 k=15;k<15+2A;k++){5(!G(1i[k])){1i[k]=[]}6 2Z=1i[k];F(" +
                    "6 l=1L;l<1L+2F;l++){2Z[l]=\"x\"}}}}h n.1m[1p.I][2E]};7.q=9(o,p){6 t,8,21=C;5(X(p)=" +
                    "=\"9\"){p={R:p}}p=p||{};5(!G(p.D)){p.D=n.2g(o)||0}p.R=p.R||1C[\\\'2M\\\'];t=n.T(o,p);8" +
                    "=n.S[t.I];5(G(8.2z)&&8.2z==8.D&&G(8.2s)){8.1d=!8.2s}M{8.1d=!!p.1d}8.2z=8.D;8.2s=" +
                    "!!8.1d;6 R=8.R;5(X(R.O)==\"9\"){21=8.R.O;R=1C.23}n.1s(t,\"1g\",9(N){5(14(N,n.2e)){1k" +
                    "(N,n.2v);1k(N,n.2x);5(8.D==7.2g(N)&&(Y(N,7.2e))){1l(N,8.1d?n.2v:n.2x)}}});6 K=t." +
                    "1O;5(K==C||K.y==0){h}6 3C=(8.1d)?9(a,b){h R(b[0],a[0])}:9(a,b){h R(a[0],b[0])};6" +
                    " 1U=!!8.1U;6 D=8.D;F(6 i=0,L=K.y;i<L;i++){6 18=K[i],1f=18.J,J=[];5(!14(18,7.2X))" +
                    "{6 Q,U=0;5(Q=1f[U]){1y{5(2l=Q.A){6 1Y=(D<2l.y)?n.1z(2l[D],1U):C;5(21)1Y=21(1Y);J" +
                    "[U]=[1Y,1f[U]]}}1q(Q=1f[++U])}J.q(3C);U=0;6 20=0;6 f=[1k,1l];5(Q=J[U]){1y{18.4o(" +
                    "Q[1])}1q(Q=J[++U])}}}5(8.P){n.B(t)}M{5(8.12){n.2a(t,8.12,!!8.3I)}}};7.u=9(o,z,p)" +
                    "{6 N;p=p||{};6 t=n.T(o,p);6 8=n.S[t.I];5(!z){8.z=C}M{5(z.W==\"3O\"&&z.E==\"2h-4p\"&&" +
                    "z.22>-1){z={\\\'u\\\':z.2t[z.22].1w}}5(z.W==\"3K\"&&z.E==\"3L\"){z={\\\'u\\\':\"/^\"+z.1w+\"/\"}" +
                    "}5(X(z)==\"4l\"&&!z.y){z=[z]}F(6 i=0,L=z.y;i<L;i++){6 u=z[i];5(X(u.u)==\"3B\"){5(u.u" +
                    ".1Q(/^\\\\/(.*)\\\\/$/)){u.u=1e 17(17.$1);u.u.3s=1N}M 5(u.u.1Q(/^9\\\\s*\\\\(([^\\\\)]*)\\\\" +
                    ")\\\\s*\\\\{(.*)}\\\\s*$/)){u.u=2k(17.$1,17.$2)}}5(u&&!G(u.D)&&(N=1M(o,\"4g\",\"4s\"))){u." +
                    "D=n.1h(N)}5((!u||!u.u)&&8.z){4t 8.z[u.D]}M{8.z=8.z||{};8.z[u.D]=u.u}}F(6 j 2T 8." +
                    "z){6 3w=1N}5(!3w){8.z=C}}h 7.2q(o)};7.B=9(t,B,p){p=p||{};5(G(B)){p.B=B}h 7.2q(t," +
                    "p)};7.2f=9(t,2i,p){t=n.T(t,p);h n.B(t,(7.S[t.I].B||0)+2i,p)};7.4C=9(t,p){h n.2f(" +
                    "t,1,p)};7.4E=9(t,p){h n.2f(t,-1,p)};7.2q=9(o,p){6 D,N,4F,4D=2O,u;6 B,P,1b,2m;6 1" +
                    "X=[],11=0,1P=0;6 t,8,V,13;p=p||{};t=n.T(o,p);8=n.S[t.I];6 B=8.B;5(G(B)){5(B<0){8" +
                    ".B=B=0}P=8.P||25;1b=B*P+1;2m=1b+P-1}6 K=t.1O;5(K==C||K.y==0){h}F(6 i=0,L=K.y;i<L" +
                    ";i++){6 18=K[i];F(6 j=0,1r=18.J.y;j<1r;j++){V=18.J[j];13=2O;5(8.z&&V.A){6 A=V.A;" +
                    "6 3r=A.y;F(D 2T 8.z){5(!13){u=8.z[D];5(u&&D<3r){6 w=n.1z(A[D]);5(u.3s&&w.3M){13=" +
                    "(w.3M(u)<0)}M 5(X(u)==\"9\"){13=!u(w,A[D])}M{13=(w!=u)}}}}}1P++;5(!13){11++;5(G(B)" +
                    "){1X.3F(V);5(11<1b||11>2m){13=1N}}}V.2N.1B=13?\"24\":\"\"}}5(G(B)){5(1b>=11){1b=11-(" +
                    "11%P);8.B=B=1b/P;F(6 i=1b,L=1X.y;i<L;i++){1X[i].2N.1B=\"\"}}}n.1s(t,\"1g\",9(c){((8." +
                    "z&&G(8.z[7.1h(c)])&&14(c,7.2w))?1l:1k)(c,7.3q)});5(8.12){n.2a(t)}6 1V=4c.48(11/P" +
                    ")+1;5(G(B)){5(8.2B){8.2B.1F=B+1}5(8.2r){8.2r.1F=1V}}5(8.2p){8.2p.1F=11}5(8.2n){8" +
                    ".2n.1F=1P}h{\\\'49\\\':8,\\\'44\\\':11,\\\'3Z\\\':1P,\\\'1V\\\':1V,\\\'B\\\':B,\\\'P\\\':P}};7.2a=9(t,10" +
                    ",p){p=p||{};p.12=10;t=n.T(t,p);6 8=n.S[t.I];6 K=t.1O;5(K==C||K.y==0){h}10=8.12;6" +
                    " f=[1k,1l];F(6 i=0,L=K.y;i<L;i++){6 18=K[i],1f=18.J,U=0,Q,20=0;5(Q=1f[U]){5(8.40" +
                    "){1y{f[20++%2](Q,10)}1q(Q=1f[++U])}M{1y{5(!1A(Q)){f[20++%2](Q,10)}}1q(Q=1f[++U])" +
                    "}}}};7.3G=9(t,D){6 2R={},K=n.T(t).1O;F(6 i=0,L=K.y;i<L;i++){6 2U=K[i];F(6 r=0,1r" +
                    "=2U.J.y;r<1r;r++){2R[n.1z(2U.J[r].A[D])]=1N}}6 2Q=[];F(6 w 2T 2R){2Q.3F(w)}h 2Q." +
                    "q()};7.27=9(p){6 A=[],26=1j.31(\"2d\");6 w,8;5(26!=C){F(6 i=0,L=26.y;i<L;i++){6 t=" +
                    "7.T(26[i]);8=7.S[t.I];5(w=Y(t,7.3y)){8.12=w}5(14(t,7.2D)){7.2y(t)}5(w=Y(t,7.3v))" +
                    "{7.2L(t,{\\\'P\\\':+w})}5((w=Y(t,7.3z))||(14(t,7.3J))){7.29(t,{\\\'D\\\':(w==C)?C:+w})}5" +
                    "(8.12&&14(t,7.3x)){7.2a(t)}}}};7.29=9(t,p){t=n.T(t,p);6 8=n.S[t.I];n.1s(t,\"1g\",9" +
                    "(c){6 E=Y(c,7.3E);5(E!=C){E=E||\"2M\";c.3D=c.3D||7.3A;1l(c,7.2e);c.2u=2k(\"\",\"1K.q(" +
                    "n,{\\\'R\\\':1C[\\\'\"+E+\"\\\']})\");5(p.D!=C){5(p.D==7.2g(c)){8.R=1C[\\\'\"+E+\"\\\']}}}});5(p." +
                    "D!=C){7.q(t,p)}};7.2L=9(t,p){t=n.T(t,p);6 8=n.S[t.I];5(8.P){n.1s(t,\"1g,3p\",9(c){" +
                    "6 E=Y(c,7.3u);5(E==\"3W\"){E=1}M 5(E==\"3T\"){E=-1}5(E!=C){c.2u=2k(\"\",\"1K.2f(n,\"+E+\"" +
                    ")\")}});5(w=Y(t,7.3H)){8.2B=1j.1J(w)}5(w=Y(t,7.3t)){8.2r=1j.1J(w)}h 7.B(t,0,p)}};" +
                    "7.2c=9(e){e=e||1c.3n;5(X(e.3o)==\"9\"){e.3o()}5(G(e.2c)){e.2c=1N}};7.2y=9(t,p){p=p" +
                    "||{};t=n.T(t,p);6 8=n.S[t.I],w;7.1s(t,\"1g\",9(N){5(14(N,7.2w)){6 1D=7.1h(N);6 1x=" +
                    "7.3G(t,1D);5(1x.y>0){5(X(p.3N)==\"9\"){1o.3N(N,1x)}M{6 2b=\\\'<2h 4m=\"1K.u(n,n)\" 2u=" +
                    "\"1K.2c(3n)\" 4q=\"\\\'+7.2D+\\\'\"><28 1w=\"\">\\\'+7.2W+\\\'</28>\\\';F(6 i=0;i<1x.y;i++){2b+=" +
                    "\\\'<28 1w=\"\\\'+1x[i]+\\\'\">\\\'+1x[i]+\\\'</28>\\\'}2b+=\\\'</2h>\\\';N.1F+=\"<4B>\"+2b}}}});5(w" +
                    "=Y(t,7.3l)){8.2p=1j.1J(w)}5(w=Y(t,7.3d)){8.2n=1j.1J(w)}};5(X(30)!=\"2H\"){30(7.27)" +
                    "}M 5(1c.2V){1c.2V(\"42\",7.27,2O)}M 5(1c.32){1c.32(\"4j\",7.27)}h 7})();\',62,291,\'||" +
                    "|||if|var|table|tdata|function||||||||return||||||this||args|sort||||filter||val" +
                    "||length|filters|cells|page|null|col|type|for|def|node|id|rows|bodies||else|cell" +
                    "|convert|pagesize|cRow|sorttype|tabledata|resolve|cRowIndex|row|nodeName|typeof|" +
                    "classValue|td|className|unfilteredrowcount|stripeclass|hideRow|hasClass|rowIndex" +
                    "|date|RegExp|tb|yr|name|pagestart|window|desc|new|tbrows|THEAD|getCellIndex|matr" +
                    "ix|document|removeClass|addClass|tableHeaderIndexes|numeric|func|tableObj|while|" +
                    "L2|processTableCells|tableCellObj|ret|section|value|colValues|do|getCellValue|is" +
                    "Hidden|display|Sort|cellIndex|nodeValue|innerHTML|childNodes|arg|numeric_comma|g" +
                    "etElementById|Table|firstAvailCol|getParent|true|tBodies|totalrows|match|replace" +
                    "|re|ignorecase|useinnertext|pagecount|innerText|unfilteredrows|cellValue|parentN" +
                    "ode|displayedCount|sortconvert|selectedIndex|alphanumeric|none||tables|auto|opti" +
                    "on|autosort|stripe|sel|cancelBubble|TABLE|SortableClassName|pageJump|getActualCe" +
                    "llIndex|select|count|tr|Function|rowCells|pageend|container_all_count|nname|cont" +
                    "ainer_filtered_count|scrape|container_count|lastdesc|options|onclick|SortedAscen" +
                    "dingClassName|FilterableClassName|SortedDescendingClassName|autofilter|lastcol|r" +
                    "owSpan|container_number|processCells|AutoFilterClassName|cellCoordinates|colSpan" +
                    "|trs|undefined|Date|o1|getTime|autopage|default|style|false|fixYear|valArray|val" +
                    "ues|numeric_converter|in|tbody|addEventListener|FilterAllLabel|NoSortClassName|f" +
                    "ormats|matrixrow|jQuery|getElementsByTagName|attachEvent|separator|prefix|cellsK" +
                    "|sortable|sorted|filtered|L3|copy|uniqueId|rowcount|RowcountPrefix|useInnerText|" +
                    "cs|getComputedStyle|thead|currentStyle|arguments|o2|FilteredRowcountPrefix|cellI" +
                    "d|event|stopPropagation|TFOOT|FilteredClassName|cellsLength|regex|PageCountPrefi" +
                    "x|AutoPageJumpPrefix|AutoPageSizePrefix|keep|AutoStripeClassName|StripeClassName" +
                    "Prefix|AutoSortColumnPrefix|AutoSortTitle|string|newSortFunc|title|SortableColum" +
                    "nPrefix|push|getUniqueColValues|PageNumberPrefix|ignorehiddenrows|AutoSortClassN" +
                    "ame|INPUT|text|search|insert|SELECT|All|number|Filter|TABLE_|previous|tFoot|tHea" +
                    "d|next|Click|getPropertyValue|total|ignoreHiddenRows|test|load|9999999999999|unf" +
                    "ilteredcount|autostripe|nosort|filterable|floor|data|to|asc|Math|IMG|currency_co" +
                    "mma|currency|TD|break|call|onload|toLowerCase|object|onchange|parseFloat|appendC" +
                    "hild|one|class|TR|TH|delete|2000|checkbox|100|1900|radio|checked|nodeType|br|pag" +
                    "eNext|filterReset|pagePrevious|filterList|50\'.split(\'|\'),0,{}))");
            this.Write("</script>\r\n<script language=\"javascript\" type=\"text/javascript\">");
            this.Write("\"use strict\";function quotedParameterString(n,t){return t||typeof n==\"undefined\"|" +
                    "|n===null?\"null\":\"\'\"+n.replace(\"\'\",\"\\\\\'\")+\"\'\"}function setDisplayProperty(n,t,i)" +
                    "{n.style.display===t||(t===\"none\"?(i&&n.style.display&&n.style.display!==\"none\"&" +
                    "&(n.style.original_display_property=n.style.display),n.style.display=t):n.style." +
                    "display=i&&n.style.original_display_property?n.style.original_display_property:t" +
                    ")}function setDisplayPropertyOnElement(n,t,i){if(n){var r=document.getElementByI" +
                    "d(n);r&&setDisplayProperty(r,t,i)}}function setDisplayPropertyOnElements(n,t,i){" +
                    "var e,f,r,u;if(n)for(e=n.split(/[\\s,;]+/),f=0;f<e.length;f++)if(logToConsole&&co" +
                    "nsole.log(\"SDPOEs\",e[f],t,i),r=document.getElementsByClassName(e[f]),r)for(u=0;u" +
                    "<r.length;u++)logToConsole&&console.log(\"sDPOEs\",r[u]),r[u]&&setDisplayProperty(" +
                    "r[u],t,i)}function showAndHideElements(n,t,i,r,u,f){logToConsole&&console.log(\"S" +
                    "AHEs\",n,t,u,f);setDisplayPropertyOnElement(n,\"none\",!1);setDisplayPropertyOnElem" +
                    "ent(t,\"inline\",!1);setDisplayPropertyOnElement(i,\"inline\",!0);setDisplayProperty" +
                    "OnElement(r,\"none\",!0);setDisplayPropertyOnElements(u,\"inline\",!0);setDisplayPro" +
                    "pertyOnElements(f,\"none\",!0)}function showElements(n,t,i,r,u){logToConsole&&cons" +
                    "ole.log(\"SE\",n,t,i,r,u);showAndHideElements(n,t,i,null,r,u)}function hideElement" +
                    "s(n,t,i,r,u){logToConsole&&console.log(\"HE\",n,t,i,r,u);showAndHideElements(t,n,n" +
                    "ull,i,u,r)}function showOrHideElement(n,t,i,r,u){if(i){var f=document.getElement" +
                    "ById(i);f&&(f.style.display===\"none\"?(setDisplayProperty(f,\"block\",!0),showEleme" +
                    "nts(n,t,null,r,u)):(setDisplayProperty(f,\"none\",!0),hideElements(n,t,null,r,u)))" +
                    "}}function initializeSingleShowHideToggleButtons(n,t,i,r,u,f,e,o){if(i){var s=do" +
                    "cument.getElementById(i);s&&(s.href=\"javascript:showOrHideElement(\"+quotedParame" +
                    "terString(r,!t)+\",\"+quotedParameterString(u,!t)+\",\"+quotedParameterString(f)+\",\"" +
                    "+quotedParameterString(e)+\",\"+quotedParameterString(o)+\")\",logToConsole&&console" +
                    ".log(\"ISSHB\",r,s.href),n?hideElements(r,u,f,e,o):t&&showElements(r,u))}}function" +
                    " initializeSingleShowHideButtons(n,t,i,r,u,f,e){var o;i&&(o=document.getElementB" +
                    "yId(i),o&&(o.href=\"javascript:showElements(\"+quotedParameterString(i,!t)+\",\"+quo" +
                    "tedParameterString(r,!t)+\",\"+quotedParameterString(u)+\",\"+quotedParameterString(" +
                    "f)+\",\"+quotedParameterString(e)+\")\",t&&!n&&(buttons.style.display=\"none\")));r&&(" +
                    "o=document.getElementById(r),o&&(o.href=\"javascript:hideElements(\"+quotedParamet" +
                    "erString(i,!t)+\",\"+quotedParameterString(r,!t)+\",\"+quotedParameterString(u)+\",\"+" +
                    "quotedParameterString(f)+\",\"+quotedParameterString(e)+\")\",n&&o.onclick()))}funct" +
                    "ion initializeMultiShowHideToggleButtons(n,t,i,r,u,f,e,o){var s,l,c,h,a,v;if(log" +
                    "ToConsole&&console.log(\"IMSHTB\",n,t,i,r,u,f,e,o),e)for(logToConsole&&console.log" +
                    "(\"IMSHTB\",e),a=e.split(/[\\s,;]+/),l=0;l<a.length;l++)if(h=document.getElementsBy" +
                    "ClassName(a[l]),h)for(s=0;s<h.length;s++)h[s]&&(c=h[s].getAttribute(i),c&&(h[s]." +
                    "href=\"javascript:showElements(\"+quotedParameterString(r+c,!t)+\",\"+quotedParamete" +
                    "rString(u+c,!t)+\",\"+quotedParameterString(f+c)+\")\",logToConsole&&console.log(\"IM" +
                    "SHTB\",a[l],c,h[s].href),t&&!n&&(h[s].style.display=\"none\")));if(o)for(logToConso" +
                    "le&&console.log(\"IMSHTB\",e),a=o.split(/[\\s,;]+/),l=0;l<a.length;l++)if(h=documen" +
                    "t.getElementsByClassName(a[l]),h)for(s=0;s<h.length;s++)h[s]&&(c=h[s].getAttribu" +
                    "te(i),c&&(v=\"hideElements(\"+quotedParameterString(r+c,!t)+\",\"+quotedParameterStr" +
                    "ing(u+c,!t)+\",\"+quotedParameterString(f+c)+\")\",h[s].href=\"javascript:\"+v,logToCo" +
                    "nsole&&console.log(\"IMSHTB\",a[l],c,h[s].href),n&&eval(v)))}var logToConsole=!0;w" +
                    "indow.onload=function(){initializeSingleShowHideToggleButtons(!1,!0,\"top-table-s" +
                    "howhide\",\"top-table-show\",\"top-table-hide\",\"top-table-hideable\");initializeSingl" +
                    "eShowHideButtons(!1,!1,\"dep-text-show\",\"dep-text-hide\",null,\"deptxt dephide\",\"de" +
                    "pshow\");initializeSingleShowHideButtons(!1,!1,\"ref-text-show\",\"ref-text-hide\",nu" +
                    "ll,\"reftxt refhide\",\"refshow\");initializeMultiShowHideToggleButtons(!0,!0,\"shbid" +
                    "\",\"show\",\"hide\",\"txt\",\"depshow\",\"dephide\");initializeMultiShowHideToggleButtons(" +
                    "!0,!0,\"shbid\",\"show\",\"hide\",\"txt\",\"refshow\",\"refhide\")};");
            this.Write(@"</script>
</head>
<body>

<a id=""top-table-showhide"" class=""top-table-showhide showhide"">
	<span id=""top-table-hide"">&#9664;</span>
	<span id=""top-table-show"">&#9658;</span>
</a>

<div id=""top-table-hideable"">
<table class=""top-table table-autostripe table-stripeclass:table-row-odd"">
	<thead>
		<tr class=""table-headers"">
			<th colspan=1></th>
			<th colspan=3>Asset Counts</th>
			<th colspan=14>Mean Values for Built-Ins</th>
		</tr>
		<tr class=""header-headers"">
			<th colspan=1></th>
			<th colspan=3></th>
			<th colspan=7>Main</th>
			<th colspan=7>Lod</th></tr>
		<tr class=""header-headers"">
			<th colspan=1></th>
			<th colspan=3></th>
			<th colspan=1>Combined</th><th colspan=3>Triangles</th><th colspan=3>Textures</th>
			<th colspan=1>Combined</th><th colspan=3>Triangles</th><th colspan=3>Textures</th>
		</tr>
		<tr class=""column-headers"">
			<th class=""txt"">Type</th>
			<th class=""num"">All</th><th class=""num"">Built-In</th><th class=""num"">Custom</th>
			<th class=""num"">Weight</th><th class=""num"">Count</th><th class=""num"">Surface</th><th class=""num"">Weight</th><th class=""num"">Dimensions</th><th class=""num"">Area</th><th class=""num"">Weight</th>
			<th class=""num"">Weight</th><th class=""num"">Count</th><th class=""num"">Surface</th><th class=""num"">Weight</th><th class=""num"">Dimensions</th><th class=""num"">Area</th><th class=""num"">Weight</th>
		</tr>
	</thead>
	<tbody>
		");
            
            #line 51 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"

			foreach (AssetSizes sizes in MeanBuiltInAssetSizes)
			{
				
            
            #line default
            #line hidden
            this.Write("<tr>\r\n\t\t\t\t\t<td class=\"txt\">");
            
            #line 55 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.AssetType));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"txt\">");
            
            #line 56 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.TotalAssetCount));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"txt\">");
            
            #line 57 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.BuiltInAssetCount));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"txt\">");
            
            #line 58 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.CustomAssetCount));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 59 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 59 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.CombinedWeight));
            
            #line default
            #line hidden
            
            #line 59 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 60 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 60 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.TrianglesCount));
            
            #line default
            #line hidden
            
            #line 60 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 61 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 61 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.TrianglesSurfaceRounded));
            
            #line default
            #line hidden
            
            #line 61 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 62 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 62 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.TrianglesWeight));
            
            #line default
            #line hidden
            
            #line 62 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"dim\">");
            
            #line 63 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedTextures) { 
            
            #line default
            #line hidden
            
            #line 63 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.TexturesDimensions));
            
            #line default
            #line hidden
            
            #line 63 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 64 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedTextures) { 
            
            #line default
            #line hidden
            
            #line 64 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.TexturesArea));
            
            #line default
            #line hidden
            
            #line 64 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 65 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Main.InitializedBoth) { 
            
            #line default
            #line hidden
            
            #line 65 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Main.TexturesWeight));
            
            #line default
            #line hidden
            
            #line 65 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 66 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 66 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.CombinedWeight));
            
            #line default
            #line hidden
            
            #line 66 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 67 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 67 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.TrianglesCount));
            
            #line default
            #line hidden
            
            #line 67 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 68 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 68 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.TrianglesSurfaceRounded));
            
            #line default
            #line hidden
            
            #line 68 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 69 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 69 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.TrianglesWeight));
            
            #line default
            #line hidden
            
            #line 69 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"dim\">");
            
            #line 70 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedTextures) { 
            
            #line default
            #line hidden
            
            #line 70 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.TexturesDimensions));
            
            #line default
            #line hidden
            
            #line 70 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 71 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedTextures) { 
            
            #line default
            #line hidden
            
            #line 71 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.TexturesArea));
            
            #line default
            #line hidden
            
            #line 71 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=\"num\">");
            
            #line 72 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (sizes.Lod.InitializedBoth) { 
            
            #line default
            #line hidden
            
            #line 72 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sizes.Lod.TexturesWeight));
            
            #line default
            #line hidden
            
            #line 72 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t</tr>");
            
            #line 73 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"

			}
		
            
            #line default
            #line hidden
            this.Write(@"	</tbody>
</table>
</div>

<table class=""main-table table-autosort table-autofilter table-filtered-rowcount:main-table-visible-rowspan table-rowcount:main-table-total-rowspan table-autostripe table-stripeclass:table-row-odd"">
	<thead>
		<tr class=""table-headers""><th colspan=22>Assets (<span id=""main-table-visible-rowspan"">");
            
            #line 82 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetCount));
            
            #line default
            #line hidden
            this.Write("</span>/<span id=\"main-table-total-rowspan\">");
            
            #line 82 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetCount));
            
            #line default
            #line hidden
            this.Write("</span>)</th></tr>\r\n\t\t<tr class=\"header-headers\">\r\n\t\t\t<th colspan=4></th>\r\n\t\t\t<th" +
                    " colspan=7>Main</th>\r\n\t\t\t<th colspan=7>Lod</th>\r\n\t\t\t<th colspan=4></th>\r\n\t\t</tr>" +
                    "\r\n\t\t<tr class=\"header-headers\">\r\n\t\t\t<th colspan=4></th>\r\n\t\t\t<th colspan=1>Combin" +
                    "ed</th><th colspan=3>Triangles</th><th colspan=3>Textures</th>\r\n\t\t\t<th colspan=1" +
                    ">Combined</th><th colspan=3>Triangles</th><th colspan=3>Textures</th>\r\n\t\t\t<th co" +
                    "lspan=2>\r\n\t\t\t\tUsages\r\n\t\t\t\t<a class=\"showhide\" id=\"dep-text-hide\">&#9664;</a>\r\n\t\t" +
                    "\t\t<a class=\"showhide\" id=\"dep-text-show\">&#9658;</a>\r\n\t\t\t</th>\r\n\t\t\t<th colspan=2" +
                    ">\r\n\t\t\t\tReferences\r\n\t\t\t\t<a class=\"showhide\" id=\"ref-text-hide\">&#9664;</a>\r\n\t\t\t\t<" +
                    "a class=\"showhide\" id=\"ref-text-show\">&#9658;</a>\r\n\t\t\t</th>\r\n\t\t</tr>\r\n\t\t<tr clas" +
                    "s=\"column-headers\">\r\n\t\t\t<th class=\"txt table-sortable:alphanumeric table-filtera" +
                    "ble\">Source<span/></th>\r\n\t\t\t<th class=\"txt table-sortable:alphanumeric table-fil" +
                    "terable\">Type<span/></th>\r\n\t\t\t<th class=\"txt table-sortable:alphanumeric table-f" +
                    "ilterable\">Category<span/></th>\r\n\t\t\t<th class=\"txt table-sortable:alphanumeric\">" +
                    "Title</th>\r\n\t\t\t<th class=\"num table-sortable:numeric\">Weight</th><th class=\"num " +
                    "table-sortable:numeric\">Count</th><th class=\"num table-sortable:numeric\">Surface" +
                    "</th><th class=\"num table-sortable:numeric\">Weight</th><th class=\"num table-sort" +
                    "able:alphanumeric\">Dimensions</th><th class=\"num table-sortable:numeric\">Area</t" +
                    "h><th class=\"num table-sortable:numeric\">Weight</th>\r\n\t\t\t<th class=\"num table-so" +
                    "rtable:numeric\">Weight</th><th class=\"num table-sortable:numeric\">Count</th><th " +
                    "class=\"num table-sortable:numeric\">Surface</th><th class=\"num table-sortable:num" +
                    "eric\">Weight</th><th class=\"num table-sortable:alphanumeric\">Dimensions</th><th " +
                    "class=\"num table-sortable:numeric\">Area</th><th class=\"num table-sortable:numeri" +
                    "c\">Weight</th>\r\n\t\t\t<th class=\"num table-sortable:numeric\">Count</th><th class=\"t" +
                    "xt table-sortable:alphanumeric\">Assets</th>\r\n\t\t\t<th class=\"num table-sortable:nu" +
                    "meric\">Count</th><th class=\"txt table-sortable:alphanumeric\">Assets</th>\r\n\t\t</tr" +
                    ">\r\n\t</thead>\r\n\t<tbody>\r\n\t\t");
            
            #line 116 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"

        {
			int assetCount = 0;
			foreach (AssetInfo asset in Assets) 
			{
				assetCount++; 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=txt>");
            
            #line 124 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.SourceType));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=txt>");
            
            #line 125 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=txt>");
            
            #line 126 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.EscapedCategory));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=nam>");
            
            #line 127 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 
					{
						if (asset.SteamId != 0) 
						{
							Write("<a href=\"{0}\" target=_blank>{1}</a>", asset.SteamLink, asset.EscapedTitle);
						}
						else
						{
							Write(asset.EscapedTitle);
						}
					}
					
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 139 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 139 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.CombinedWeight));
            
            #line default
            #line hidden
            
            #line 139 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 140 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 140 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.TrianglesCount));
            
            #line default
            #line hidden
            
            #line 140 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 141 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 141 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.TrianglesSurfaceRounded));
            
            #line default
            #line hidden
            
            #line 141 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 142 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 142 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.TrianglesWeight));
            
            #line default
            #line hidden
            
            #line 142 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=dim>");
            
            #line 143 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTexture) { 
            
            #line default
            #line hidden
            
            #line 143 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.TextureDimensions));
            
            #line default
            #line hidden
            
            #line 143 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 144 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTexture) { 
            
            #line default
            #line hidden
            
            #line 144 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.TextureArea));
            
            #line default
            #line hidden
            
            #line 144 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 145 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Main.InitializedTexture) { 
            
            #line default
            #line hidden
            
            #line 145 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Main.TextureWeight));
            
            #line default
            #line hidden
            
            #line 145 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 146 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.FallbackLod.InitializedBoth) { 
            
            #line default
            #line hidden
            
            #line 146 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FallbackLod.CombinedWeight));
            
            #line default
            #line hidden
            
            #line 146 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 147 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Lod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 147 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Lod.TrianglesCount));
            
            #line default
            #line hidden
            
            #line 147 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 148 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Lod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 148 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Lod.TrianglesSurfaceRounded));
            
            #line default
            #line hidden
            
            #line 148 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 149 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.FallbackLod.InitializedTriangles) { 
            
            #line default
            #line hidden
            
            #line 149 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FallbackLod.TrianglesWeight));
            
            #line default
            #line hidden
            
            #line 149 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=dim>");
            
            #line 150 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Lod.InitializedTexture) { 
            
            #line default
            #line hidden
            
            #line 150 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Lod.TextureDimensions));
            
            #line default
            #line hidden
            
            #line 150 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 151 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.Lod.InitializedTexture) { 
            
            #line default
            #line hidden
            
            #line 151 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.Lod.TextureArea));
            
            #line default
            #line hidden
            
            #line 151 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 152 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 if (asset.FallbackLod.InitializedBoth) { 
            
            #line default
            #line hidden
            
            #line 152 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FallbackLod.TextureWeight));
            
            #line default
            #line hidden
            
            #line 152 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 153 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.DependentCount));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=txt>");
            
            #line 154 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"

					{
						int references = asset.DependentCount;
						if (references > 0)
						{
							string id = assetCount.ToString() + "dep";
							Write("<a shbid={0} class=dephide id=hide{0}>&#9664;</a>", id);
							Write("<a shbid={0} class=depshow id=show{0}>&#9658;</a>", id);
							Write("<span class=deptxt id=txt{0}>", id);

							foreach (Reference reference in asset.Dependents.OrderBy(r => r.ReferenceType).ThenBy(r => r.Name.ToLowerInvariant()))
							{
								references --;

								Write("<span class=name>");

								if (reference.SteamId > 0)
								{
									Write("<a href=\"{0}\" target=_blank>{1}</a>", reference.SteamLink, reference.EscapedTitle);
								}
								else
								{
									Write(reference.EscapedTitle);
								}

								Write("</span>");

								if (references > 0)
								{
									Write("</br>");
								}
							}

							Write("</span>");
						}
					}
					
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t\t<td class=num>");
            
            #line 191 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.ReferenceCount));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t<td class=txt><span class=rtxt>");
            
            #line 192 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 
					{
						int references = asset.ReferenceCount;
						if (references > 0)
						{
							string id = assetCount.ToString() + "ref";
							Write("<a shbid={0} class=refhide id=hide{0}>&#9664;</a>", id);
							Write("<a shbid={0} class=refshow id=show{0}>&#9658;</a>", id);
							Write("<span class=reftxt id=txt{0}>", id);

							foreach (Reference reference in asset.References.OrderBy(r => r.ReferenceType).ThenBy(r => r.Name.ToLowerInvariant()))
							{
								references --;

								if (reference.Missing)
								{
									Write("<span class=miss>");
								}

								Write("<span class=name>");
								Write(reference.ReferenceType);
								Write(": ");

								if (reference.SteamId > 0)
								{
									Write("<a href=\"{0}\" target=_blank>{1}</a>", reference.SteamLink, reference.EscapedTitle);
								}
								else
								{
									Write(reference.EscapedTitle);
								}

								Write("</span>");

								if (reference.Missing)
								{
									Write("</span>");
								}

								if (references > 0)
								{
									Write("<br/>");
								}
							}

							Write("</span>");
						}
					}
					
            
            #line default
            #line hidden
            this.Write("</span></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t");
            
            #line 242 "D:\Jonas\Development\Cities Skylines\Mods\Assetteer\wtmcsAsseteer\Reporter\Template\HtmlReportTemplate.tt"
 
			} 
		} 
            
            #line default
            #line hidden
            this.Write("\t</tbody>\r\n</table>\r\n\r\n</body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class HtmlReportTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
